---
# tasks file for lighthouse-role
    - name: Install git
      become: true
      yum:
        name: git
        state: present
    - name: Pull lighthouse from git
      git:
        repo: "{{ lighthouse_git }}"
        version: master
        dest: "/usr/share/nginx/html"
        single_branch: yes
    - name: Make lighthouse conf file from template
      become: true
      template:
        src: "template/lighthouse.conf.j2"
        dest: "/etc/nginx/conf.d/default.conf"
        mode: 0755
      notify: reload-nginx
      tags: lighthouse_ready
